repos:
  - repo: https://github.com/commit-check/commit-check
    rev: v2.2.1
    hooks:
      - id: check-branch
        stages: [pre-commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.12.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse
        stages: [pre-commit]
