#
# On commit push or pull request events, verifies the project builds successfully on JDK 17, 21, 25.
# If so, its Dependency Snapshot is submitted.
#
name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: pdfclown/.github/.github/workflows/build.yml@main
    permissions:
      contents: write
      security-events: write
    with:
      # FIXME: temporarily disables Java 25 until maven-shade-plugin supports it, to avoid polluting
      #        logs with noisy errors (our release target is Java 17).
      java_matrix: "[ '17', '21' ]"
    secrets: inherit
