name: Build CI

on: [push, pull_request]

jobs:
  build:
    name: Java ${{ matrix.Java }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '21', '25' ]
      fail-fast: false
    env:
      JAVA_DISTRO: 'temurin'

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up build JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ env.JAVA_DISTRO }}
        cache: maven

    - name: Set up tool JDK
      uses: actions/setup-java@v5
      with:
        java-version-file: '.tool-versions'
        distribution: ${{ env.JAVA_DISTRO }}
        cache: maven

    - name: Build with Maven
      run: mvn clean verify --batch-mode -e -Djava.version=${{ matrix.java }}

    - name: Submit Dependency Snapshot
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.java == '11'
      uses: advanced-security/maven-dependency-submission-action@v5

