#
# On pushed release tags, creates a GitHub Release draft.
#
# NOTE: Generated notes are configured via `.github/release.yml`.
#
name: GitHub Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  REPO_TITLE: 'pdfClown Common'

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release (draft)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$REPO_TITLE ${tag#v}" \
              --generate-notes \
              --fail-on-no-commits \
              --draft
